#!/usr/bin/env python3
"""Render docs/GATEWAY.md from schema_map.py output.

The doc is *derived*, never hand-edited: a hand-maintained list of an
undocumented, unversioned vendor schema is a future lie. Re-run the mapper and
re-run this.

Honesty rule this file enforces: a namespace with zero discovered fields is
reported as **undiscovered**, not as empty. The oracle only suggests names that
are lexically close to the probe, so silence is a limit of the method, not a
fact about the schema. Collapsing those two would turn a coverage gap into a
confident claim of absence.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

PRODUCTS = [
    ("Hexowatch", ("Watch",)),
    ("Hexomatic", ("Hexomatic", "Scraper", "Automation")),
    ("Hexospark", ("Hexospark",)),
    ("Hexometer", ("Hexometer", "Property")),
    ("Hexofy", ("Hexofy",)),
    ("Hexoscope", ("Hexoscope",)),
    ("Account / shared", ("User", "Billing", "Team", "Admin", "Alert", "Task",
                          "Keyword", "Shortlink", "Tag", "Notification")),
]
DANGEROUS = ("Billing", "Admin", "Payment", "Package", "Subscription")


def product_of(namespace: str) -> str:
    for label, prefixes in PRODUCTS:
        if any(namespace.startswith(p) for p in prefixes):
            return label
    return "Unclassified"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", default="/tmp/hexact-schema/hexowatch.json")
    parser.add_argument("--out", default="docs/GATEWAY.md")
    parser.add_argument(
        "--allow-resolver-entry", action="store_true",
        help="render even if the walk entered resolvers (unsafe; only with cause)",
    )
    args = parser.parse_args()

    data = json.loads(Path(args.input).read_text(encoding="utf-8"))

    # Ship gate. The whole claim of this reference is that it was recovered
    # WITHOUT side effects; a walk that entered resolvers did not honour that,
    # so rendering it would print a false provenance. Refuse by default. This is
    # decidable and cheap, and it has already caught a real regression (a type
    # probe that dropped the bogus-argument guard entered 34 resolvers).
    resolvers = data.get("resolvers_entered") or []
    if resolvers and not args.allow_resolver_entry:
        print(
            f"REFUSING to render {args.out}: {len(resolvers)} resolver(s) were "
            f"entered during this walk, so it is not provably side-effect-free.\n"
            f"  first few: {resolvers[:5]}\n"
            f"Fix tools/schema_map.py so EVERY probe carries the bogus argument, "
            f"re-run the walk, and render the clean result. Override with "
            f"--allow-resolver-entry only if you understand exactly why.",
            file=sys.stderr,
        )
        return 2

    namespaces = data["namespaces"]

    grouped: dict[str, list[tuple[str, str, dict]]] = defaultdict(list)
    for key, entry in sorted(namespaces.items()):
        kind, _, name = key.partition(":")
        grouped[product_of(name)].append((name, kind, entry))

    total_fields = sum(len(e["fields"]) for e in namespaces.values())
    undiscovered = [k for k, e in namespaces.items() if not e["fields"]]

    lines: list[str] = []
    add = lines.append
    add("# The Hexact GraphQL gateway — recovered schema")
    add("")
    add("**Generated by `tools/schema_map.py`. Do not hand-edit.**")
    add("")
    add(f"Source: `{data['url']}`. The vendor publishes no schema for this "
        "endpoint and Apollo introspection is disabled, so every name below was "
        "recovered from validator error messages.")
    add("")
    add(f"- **{len(namespaces)} namespaces** "
        f"({sum(1 for k in namespaces if k.startswith('query:'))} query, "
        f"{sum(1 for k in namespaces if k.startswith('mutation:'))} mutation)")
    arg_count = sum(
        len(s.get("required_arguments", [])) + len(s.get("optional_arguments", []))
        for e in namespaces.values() for s in e["fields"].values()
    )
    typed = sum(1 for e in namespaces.values()
                for s in e["fields"].values() if s.get("returns"))
    add(f"- **{total_fields} fields**, **{arg_count} arguments**, "
        f"{typed} with a recovered return type")
    add(f"- {data['request_count']} requests, **{len(data['resolvers_entered'])} "
        "resolvers entered** (must be 0)")
    add("")
    add("## How this was recovered, and why it is inert")
    add("")
    add("No credential is ever sent, and **every probe carries a deliberately "
        "invalid argument**. That second rule is load-bearing rather than "
        "decorative: a mutation field with no *required* arguments otherwise "
        "reaches its resolver and runs. Measured — "
        "`mutation { WatchOps { exportAll { __typename } } }` returned "
        "`ExportAllType`, i.e. the export actually executed, unauthenticated. "
        "Adding `(zzzNotAnArg: 1)` makes the document fail validation, so "
        "`data` is null and no resolver is entered, while the same error list "
        "still names every required argument.")
    add("")
    add("The run self-checks this: any probe whose response carried a non-null "
        "`data` is counted in `resolvers_entered`, which is reported above and "
        "must be zero.")
    add("")
    add("## One gateway, four hostnames")
    add("")
    add("`api.hexowatch.com`, `api.hexomatic.com`, `api.hexospark.com` and "
        "`api.hexometer.com` all serve **the same** `/v2/ql`. Measured by "
        "sending four different probes to all four hosts and comparing "
        "SHA-256 of the response bodies: byte-identical in every case. So a "
        "hostname tells you nothing about which product a route belongs to — "
        "identify products by namespace prefix, never by host.")
    add("")
    add("**Consequence:** \"Hexospark and Hexofy have no API\" is true only of "
        "REST. Both have namespaces here.")
    add("")

    if undiscovered:
        add("## Coverage limit — read this before concluding anything is absent")
        add("")
        add(f"{len(undiscovered)} namespaces returned **no** field names. That "
            "means *not discovered*, *not* empty. The oracle only suggests "
            "names lexically close to the probe, so a namespace whose fields "
            "share no prefix with any seed stays invisible. Treat these as "
            "UNKNOWN:")
        add("")
        add("> " + ", ".join(f"`{k}`" for k in sorted(undiscovered)))
        add("")

    add("## Never call these")
    add("")
    add("The session token this gateway wants reaches the **whole account**, "
        "including billing. `hexact/graphql.py` enforces an allowlist checked "
        "before the request is built. These namespaces are refused by "
        "construction:")
    add("")
    for key in sorted(namespaces):
        name = key.partition(":")[2]
        if any(d in name for d in DANGEROUS):
            add(f"- `{name}`")
    add("")

    for label, _ in PRODUCTS + [("Unclassified", ())]:
        entries = grouped.get(label)
        if not entries:
            continue
        add(f"## {label}")
        add("")
        for name, kind, entry in entries:
            fields = entry["fields"]
            if not fields:
                add(f"### `{kind} {name}` — fields UNKNOWN (not discovered)")
                add("")
                continue
            add(f"### `{kind} {name}` — {len(fields)} field(s)")
            add("")
            add("| Field | Returns | Required | Optional |")
            add("| --- | --- | --- | --- |")
            for field, spec in sorted(fields.items()):
                required = ", ".join(
                    f"`{a['name']}: {a['type']}`"
                    for a in spec.get("required_arguments", [])) or "—"
                optional = ", ".join(
                    f"`{a['name']}: {a['type']}`"
                    for a in spec.get("optional_arguments", [])) or "—"
                returns = f"`{spec['returns']}`" if spec.get("returns") else "—"
                add(f"| `{field}` | {returns} | {required} | {optional} |")
            add("")

    Path(args.out).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{args.out}: {len(namespaces)} namespaces, {total_fields} fields, "
          f"{len(undiscovered)} undiscovered")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
