#!/usr/bin/env python3
"""Render docs/TYPES.md from tools/type_map.py output.

`GATEWAY.md` answers "what can I call". This answers "what comes back", which is
the half that decides whether a query can be written at all: GraphQL rejects a
document with no selection set, so an unknown return type is an uncallable
field.

Two honesty rules, both inherited from the sibling renderer because the same
mistakes are available here:

- A type with zero discovered fields is **undiscovered**, never empty. The
  suggester only offers names within an edit-distance bound of the probe, so
  silence is a fact about the seeds, not about the schema.
- A walk that entered a resolver is not publishable. The gate below is the same
  one that already caught a real regression in the field walk.

It also emits, per type, a paste-ready selection set of that type's **leaf**
fields. That line is the actual deliverable for anyone writing a query: object
fields are omitted because selecting one without its own selection set is a
validation error, and including them would produce a snippet that never works.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from render_gateway_doc import PRODUCTS, product_of  # noqa: E402


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", default="/tmp/hexact-types/v1.json")
    parser.add_argument("--out", default="docs/TYPES.md")
    parser.add_argument("--allow-resolver-entry", action="store_true")
    args = parser.parse_args()

    data = json.loads(Path(args.input).read_text(encoding="utf-8"))

    resolvers = data.get("resolvers_entered") or []
    if resolvers and not args.allow_resolver_entry:
        print(
            f"REFUSING to render {args.out}: {len(resolvers)} resolver(s) were "
            f"entered during this walk, so it is not provably side-effect-free.\n"
            f"  first few: {resolvers[:5]}\n"
            f"Fix tools/type_map.py so the path field always carries the bogus "
            f"argument, re-run the walk, and render the clean result.",
            file=sys.stderr,
        )
        return 2

    types: dict[str, dict] = data["types"]
    grouped: dict[str, list[tuple[str, dict]]] = defaultdict(list)
    for name, entry in sorted(types.items()):
        # The namespace the type was reached through decides its product. A type
        # name alone does not: `BaseMutationResponse` is shared by all six.
        namespace = entry["path"].split()[1].split(".")[0]
        grouped[product_of(namespace)].append((name, entry))

    known = {n: e for n, e in types.items() if e["fields"]}
    undiscovered = sorted(n for n, e in types.items() if not e["fields"])
    subfields = sum(len(e["fields"]) for e in types.values())

    lines: list[str] = []
    add = lines.append
    add("# The Hexact gateway — recovered return-type shapes")
    add("")
    add("**Generated by `tools/type_map.py`. Do not hand-edit.**")
    add("")
    add(f"Source: `{data['url']}`. Recovered from validator error messages with "
        "no credential and no resolver entered, the same way "
        "[`GATEWAY.md`](GATEWAY.md) was — one level deeper.")
    add("")
    add(f"- **{len(types)} types** walked, **{len(known)} with recovered fields**, "
        f"{len(undiscovered)} undiscovered")
    add(f"- **{subfields} subfields**, {data['request_count']} requests, "
        f"**{len(resolvers)} resolvers entered** (must be 0)")
    add("")
    add("## Why this file exists")
    add("")
    add("`GATEWAY.md` stops at the return type's *name*. GraphQL will not accept "
        "a document that selects an object without naming its subfields, so a "
        "field whose type is opaque is a field you cannot call. Everything here "
        "was recovered from `Cannot query field \"idZz\" on type "
        "\"WatchPropertyType\". Did you mean \"id\"?` — the same suggester, "
        "asked about output types.")
    add("")
    add("**Inert by construction.** The path field in every probe carries a "
        "deliberately invalid argument, which fails validation for the whole "
        "document, so no resolver on any level runs. The walker asserts this "
        "per response and aborts on the first non-null `data` rather than "
        "tallying breaches afterwards.")
    add("")
    add("## Coverage limit — read before concluding a field does not exist")
    add("")
    add("Reach is bounded by edit distance from the probe, so this is a **lower "
        "bound**. Measured: the type `webhook` reported zero fields until "
        "`eventZz` was added to the seeds — it has `events`, and none of "
        "`id`/`url`/`type`/`subscriptionId`, so every obvious seed missed it. "
        "A type listed with no fields was **not reached**; it is not empty.")
    if undiscovered:
        add("")
        add("> " + ", ".join(f"`{n}`" for n in undiscovered))
    add("")
    add("## How to read an entry")
    add("")
    add("`leaf` is a scalar or enum — selectable directly. Anything else is the "
        "object type that field returns, and needs its own selection set; look "
        "it up in this file. The **Selection** line under each table is a "
        "paste-ready set of that type's leaves only.")
    add("")

    for label, _ in PRODUCTS + [("Unclassified", ())]:
        entries = grouped.get(label)
        if not entries:
            continue
        add(f"## {label}")
        add("")
        for name, entry in entries:
            if not entry["fields"]:
                add(f"### `{name}` — fields UNKNOWN (not reached)")
                add("")
                add(f"Reached via `{entry['path']}`.")
                add("")
                continue
            add(f"### `{name}` — {len(entry['fields'])} field(s)")
            add("")
            add(f"Reached via `{entry['path']}`.")
            add("")
            add("| Field | Type |")
            add("| --- | --- |")
            for field, field_type in entry["fields"].items():
                add(f"| `{field}` | {f'`{field_type}`' if field_type else 'leaf'} |")
            leaves = [f for f, t in entry["fields"].items() if not t]
            if leaves:
                add("")
                add(f"Selection: `{{ {' '.join(leaves)} }}`")
            add("")

    Path(args.out).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{args.out}: {len(types)} types, {len(known)} with fields, "
          f"{subfields} subfields, {len(undiscovered)} undiscovered")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
